name = "systematic-push"
main = "src/index.js"
compatibility_date = "2025-01-01"

[triggers]
crons = ["*/2 * * * *"]

[[kv_namespaces]]
binding = "STORE"
id = "e807161bfaeb4460ae4913edb700ad89"

[vars]
VAPID_SUBJECT = "mailto:archieperkins0@gmail.com"
VAPID_PUBLIC_KEY = "BEA3rRfmpbVjvaU7ZL_Y2xHrhJnnM6o7XenpDG_Y4x_t5OWjFQ_DQSEeCLZGtB-B6fFF1CDRxZu3iZgAXR2YAcQ"
# VAPID_PRIVATE_KEY is set as a secret — see setup instructions
